source:
  - 'package.json'

dependencyTypes:
  - dependencies
  - devDependencies

semverRange: '^'

versionGroups:
  - dependencies:
      - '@aibos/**'
    packages:
      - '**'
    isIgnored: true
