name: Dependency Health Check

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  schedule:
    # Run daily at 2 AM UTC
    - cron: "0 2 * * *"

jobs:
  deps-check:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [20, 22]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Guard internal workspace links
        run: node scripts/check-internal-workspace.js

      - name: Workspace doctor (manypkg)
        run: pnpm deps:manypkg-check
        continue-on-error: true

      - name: Dependency housekeeping (non-blocking)
        run: pnpm deps:ranges && pnpm deps:list
        continue-on-error: true

      - name: Check for external updates
        run: pnpm deps:ncu-check
        continue-on-error: true

      - name: Verify installation still works
        run: pnpm install --frozen-lockfile

      - name: Run dependency audit
        run: pnpm deps:audit
